services:
  web:
    container_name: web
    env_file:
      - ./apps/web/.env
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  api:
    container_name: api
    env_file:
      - ./apps/api/.env
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: db
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:


volumes:
  postgres_data:
