services:
  web:
    env_file:
      - ./apps/web/.env.local
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  api:
    env_file:
      - ./apps/api/.env
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - .env.db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:


volumes:
  postgres_data:
